// Start of user code Copyright
/*******************************************************************************
 * Copyright (c) 2012 IBM Corporation and others.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * and Eclipse Distribution License v. 1.0 which accompanies this distribution.
 *  
 * The Eclipse Public License is available at http://www.eclipse.org/legal/epl-v10.html
 * and the Eclipse Distribution License is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * Contributors:
 *
 *     Russell Boykin       - initial API and implementation
 *     Alberto Giammaria    - initial API and implementation
 *     Chris Peters         - initial API and implementation
 *     Gianluca Bernardini  - initial API and implementation
 *     Michael Fiedler      - Bugzilla adpater implementations
 *     Jad El-khoury        - initial implementation of code generator (https://bugs.eclipse.org/bugs/show_bug.cgi?id=422448)
 * 
 * This file is generated by org.eclipse.lyo.oslc4j.codegenerator
 *******************************************************************************/
// End of user code

package org.eclipse.lyo.oslc.domains.auto;

import org.eclipse.lyo.oslc4j.core.model.OslcConstants;


// Start of user code imports
// End of user code

public interface Oslc_autoDomainConstants
{
    // Start of user code user constants
    // End of user code

    public static String AUTOMATION_DOMAIN = "http://open-services.net/ns/auto#";
    public static String AUTOMATION_NAMSPACE = "http://open-services.net/ns/auto#";
    public static String AUTOMATION_NAMSPACE_PREFIX = "oslc_auto";

    public static String AUTOMATIONPLAN_PATH = "automationPlan";
    public static String AUTOMATIONPLAN_NAMESPACE = AUTOMATION_NAMSPACE; //namespace of the rdfs:class the resource describes
    public static String AUTOMATIONPLAN_LOCALNAME = "AutomationPlan"; //localName of the rdfs:class the resource describes
    public static String AUTOMATIONPLAN_TYPE = AUTOMATIONPLAN_NAMESPACE + AUTOMATIONPLAN_LOCALNAME; //fullname of the rdfs:class the resource describes
    public static String AUTOMATIONREQUEST_PATH = "automationRequest";
    public static String AUTOMATIONREQUEST_NAMESPACE = AUTOMATION_NAMSPACE; //namespace of the rdfs:class the resource describes
    public static String AUTOMATIONREQUEST_LOCALNAME = "AutomationRequest"; //localName of the rdfs:class the resource describes
    public static String AUTOMATIONREQUEST_TYPE = AUTOMATIONREQUEST_NAMESPACE + AUTOMATIONREQUEST_LOCALNAME; //fullname of the rdfs:class the resource describes
    public static String AUTOMATIONRESULT_PATH = "automationResult";
    public static String AUTOMATIONRESULT_NAMESPACE = AUTOMATION_NAMSPACE; //namespace of the rdfs:class the resource describes
    public static String AUTOMATIONRESULT_LOCALNAME = "AutomationResult"; //localName of the rdfs:class the resource describes
    public static String AUTOMATIONRESULT_TYPE = AUTOMATIONRESULT_NAMESPACE + AUTOMATIONRESULT_LOCALNAME; //fullname of the rdfs:class the resource describes
    public static String PARAMETERINSTANCE_PATH = "parameterInstance";
    public static String PARAMETERINSTANCE_NAMESPACE = AUTOMATION_NAMSPACE; //namespace of the rdfs:class the resource describes
    public static String PARAMETERINSTANCE_LOCALNAME = "ParameterInstance"; //localName of the rdfs:class the resource describes
    public static String PARAMETERINSTANCE_TYPE = PARAMETERINSTANCE_NAMESPACE + PARAMETERINSTANCE_LOCALNAME; //fullname of the rdfs:class the resource describes
}
