// Start of user code Copyright
/*
 * Copyright (c) 2025 Contributors to the Eclipse Foundation
 *
 * See the NOTICE file(s) distributed with this work for additional
 * information regarding copyright ownership.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0, or the Eclipse Distribution License 1.0
 * which is available at http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: EPL-2.0 OR BSD-3-Clause
 *
 * This file is generated by Lyo Designer (https://www.eclipse.org/lyo/)
 */
// End of user code

package org.eclipse.lyo.oslc.domains;

import java.util.concurrent.ConcurrentHashMap;
import javax.xml.namespace.QName;

// Start of user code imports
// End of user code

public class Dcterms {
  private static final ConcurrentHashMap<String, QName> CACHE = new ConcurrentHashMap<>();

  public static final String NS = DctermsVocabularyConstants.DUBLIN_CORE_NAMSPACE;
  public static final String PREFIX = DctermsVocabularyConstants.DUBLIN_CORE_NAMSPACE_PREFIX;

  // static class
  private Dcterms() {}

  public static QName of(String local) {
    return get(local);
  }

  /**
   * An entity responsible for making contributions to the resource.
   */
  public static final String CONTRIBUTOR_PROP = NS + "contributor";

  /**
   * Recommended practice is to describe the date, date/time, or period of time as recommended for the property Date, of which this is a subproperty.
   */
  public static final String CREATED_PROP = NS + "created";

  /**
   * Recommended practice is to identify the creator with a URI. If this is not possible or feasible, a literal value that identifies the creator may be provided.
   */
  public static final String CREATOR_PROP = NS + "creator";

  /**
   * Date may be used to express temporal information at any level of granularity. Recommended practice is to express the date, date/time, or period of time according to ISO 8601-1 [ISO 8601-1] or a published profile of the ISO standard, such as the W3C Note on Date and Time Formats [W3CDTF] or the Extended Date/Time Format Specification [EDTF]. If the full date is unknown, month and year (YYYY-MM) or just year (YYYY) may be used. Date ranges may be specified using ISO 8601 period of time specification in which start and end dates are separated by a '/' (slash) character. Either the start or end date may be missing.
   */
  public static final String DATE_PROP = NS + "date";

  /**
   * Description may include but is not limited to: an abstract, a table of contents, a graphical representation, or a free-text account of the resource.
   */
  public static final String DESCRIPTION_PROP = NS + "description";

  /**
   * This property is intended to be used with non-literal values. This property is an inverse property of Is Part Of.
   */
  public static final String HASPART_PROP = NS + "hasPart";

  /**
   * Recommended practice is to identify the resource by means of a string conforming to an identification system. Examples include International Standard Book Number (ISBN), Digital Object Identifier (DOI), and Uniform Resource Name (URN). Persistent identifiers should be provided as HTTP URIs.
   */
  public static final String IDENTIFIER_PROP = NS + "identifier";

  /**
   * This property is intended to be used with non-literal values. This property is an inverse property of Has Part.
   */
  public static final String ISPARTOF_PROP = NS + "isPartOf";

  /**
   * Changes in version imply substantive changes in content rather than differences in format. This property is intended to be used with non-literal values. This property is an inverse property of Has Version.
   */
  public static final String ISVERSIONOF_PROP = NS + "isVersionOf";

  /**
   * Recommended practice is to describe the date, date/time, or period of time as recommended for the property Date, of which this is a subproperty.
   */
  public static final String MODIFIED_PROP = NS + "modified";

  /**
   * Recommended practice is to identify the related resource by means of a URI. If this is not possible or feasible, a string conforming to a formal identification system may be provided.
   */
  public static final String RELATION_PROP = NS + "relation";

  /**
   * This property is intended to be used with non-literal values. The described resource may be derived from the related resource in whole or in part. Best practice is to identify the related resource by means of a URI or a string conforming to a formal identification system.
   */
  public static final String SOURCE_PROP = NS + "source";

  /**
   * Recommended practice is to refer to the subject with a URI. If this is not possible or feasible, a literal value that identifies the subject may be provided. Both should preferably refer to a subject in a controlled vocabulary.
   */
  public static final String SUBJECT_PROP = NS + "subject";

  /**
   * A name given to the resource.
   */
  public static final String TITLE_PROP = NS + "title";

  /**
   * Recommended practice is to use a controlled vocabulary such as the DCMI Type Vocabulary [DCMI-TYPE]. To describe the file format, physical medium, or dimensions of the resource, use the property Format.
   */
  public static final String TYPE_PROP = NS + "type";

  /**
   * An entity responsible for making contributions to the resource.
   */
  public static QName contributor() {
    return get("contributor");
  }

  /**
   * Recommended practice is to describe the date, date/time, or period of time as recommended for the property Date, of which this is a subproperty.
   */
  public static QName created() {
    return get("created");
  }

  /**
   * Recommended practice is to identify the creator with a URI. If this is not possible or feasible, a literal value that identifies the creator may be provided.
   */
  public static QName creator() {
    return get("creator");
  }

  /**
   * Date may be used to express temporal information at any level of granularity. Recommended practice is to express the date, date/time, or period of time according to ISO 8601-1 [ISO 8601-1] or a published profile of the ISO standard, such as the W3C Note on Date and Time Formats [W3CDTF] or the Extended Date/Time Format Specification [EDTF]. If the full date is unknown, month and year (YYYY-MM) or just year (YYYY) may be used. Date ranges may be specified using ISO 8601 period of time specification in which start and end dates are separated by a '/' (slash) character. Either the start or end date may be missing.
   */
  public static QName date() {
    return get("date");
  }

  /**
   * Description may include but is not limited to: an abstract, a table of contents, a graphical representation, or a free-text account of the resource.
   */
  public static QName description() {
    return get("description");
  }

  /**
   * This property is intended to be used with non-literal values. This property is an inverse property of Is Part Of.
   */
  public static QName hasPart() {
    return get("hasPart");
  }

  /**
   * Recommended practice is to identify the resource by means of a string conforming to an identification system. Examples include International Standard Book Number (ISBN), Digital Object Identifier (DOI), and Uniform Resource Name (URN). Persistent identifiers should be provided as HTTP URIs.
   */
  public static QName identifier() {
    return get("identifier");
  }

  /**
   * This property is intended to be used with non-literal values. This property is an inverse property of Has Part.
   */
  public static QName isPartOf() {
    return get("isPartOf");
  }

  /**
   * Changes in version imply substantive changes in content rather than differences in format. This property is intended to be used with non-literal values. This property is an inverse property of Has Version.
   */
  public static QName isVersionOf() {
    return get("isVersionOf");
  }

  /**
   * Recommended practice is to describe the date, date/time, or period of time as recommended for the property Date, of which this is a subproperty.
   */
  public static QName modified() {
    return get("modified");
  }

  /**
   * Recommended practice is to identify the related resource by means of a URI. If this is not possible or feasible, a string conforming to a formal identification system may be provided.
   */
  public static QName relation() {
    return get("relation");
  }

  /**
   * This property is intended to be used with non-literal values. The described resource may be derived from the related resource in whole or in part. Best practice is to identify the related resource by means of a URI or a string conforming to a formal identification system.
   */
  public static QName source() {
    return get("source");
  }

  /**
   * Recommended practice is to refer to the subject with a URI. If this is not possible or feasible, a literal value that identifies the subject may be provided. Both should preferably refer to a subject in a controlled vocabulary.
   */
  public static QName subject() {
    return get("subject");
  }

  /**
   * A name given to the resource.
   */
  public static QName title() {
    return get("title");
  }

  /**
   * Recommended practice is to use a controlled vocabulary such as the DCMI Type Vocabulary [DCMI-TYPE]. To describe the file format, physical medium, or dimensions of the resource, use the property Format.
   */
  public static QName type() {
    return get("type");
  }

  private static QName get(String local) {
    return CACHE.computeIfAbsent(local, l -> new QName(NS, l, PREFIX));
  }
}
