// Start of user code Copyright
/*
 * Copyright (c) 2025 Contributors to the Eclipse Foundation
 *
 * See the NOTICE file(s) distributed with this work for additional
 * information regarding copyright ownership.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0, or the Eclipse Distribution License 1.0
 * which is available at http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: EPL-2.0 OR BSD-3-Simple
 *
 * This file is generated by Lyo Designer (https://www.eclipse.org/lyo/)
 */
// End of user code

package org.eclipse.lyo.oslc.domains;

import java.util.concurrent.ConcurrentHashMap;
import javax.xml.namespace.QName;

// Start of user code imports
// End of user code

public class Foaf {
  private static final ConcurrentHashMap<String, QName> CACHE = new ConcurrentHashMap<>();

  public static final String NS = FoafVocabularyConstants.FOAF_NAMSPACE;
  public static final String PREFIX = FoafVocabularyConstants.FOAF_NAMSPACE_PREFIX;

  // static class
  private Foaf() {}

  public static QName of(String local) {
    return get(local);
  }

  /**
   * The Agent class is the class of agents; things that do stuff. A well known sub-class is Person, representing people. Other kinds of agents include Organization and Group. The Agent class is useful in a few places in FOAF where Person would have been overly specific. For example, the IM chat ID properties such as jabberID are typically associated with people, but sometimes belong to software bots.
   */
  public static final String AGENT_CLASS = NS + "Agent";

  /**
   * The Person class represents people. Something is a Person if it is a person. We don't nitpic about whether they're alive, dead, real, or imaginary. The Person class is a sub-class of the Agent class, since all people are considered 'agents' in FOAF.
   */
  public static final String PERSON_CLASS = NS + "Person";

  /**
   * The familyName property is provided (alongside givenName) for use when describing parts of people's names. Although these concepts do not capture the full range of personal naming styles found world-wide, they are commonly used and have some value.
   */
  public static final String FAMILYNAME_PROP = NS + "familyName";

  /**
   * The givenName property is provided (alongside familyName) for use when describing parts of people's names. Although these concepts do not capture the full range of personal naming styles found world-wide, they are commonly used and have some value.
   */
  public static final String GIVENNAME_PROP = NS + "givenName";

  /**
   * The name of something is a simple textual string.
   */
  public static final String NAME_PROP = NS + "name";

  /**
   * The familyName property is provided (alongside givenName) for use when describing parts of people's names. Although these concepts do not capture the full range of personal naming styles found world-wide, they are commonly used and have some value.
   */
  public static QName familyName() {
    return get("familyName");
  }

  /**
   * The givenName property is provided (alongside familyName) for use when describing parts of people's names. Although these concepts do not capture the full range of personal naming styles found world-wide, they are commonly used and have some value.
   */
  public static QName givenName() {
    return get("givenName");
  }

  /**
   * The name of something is a simple textual string.
   */
  public static QName name() {
    return get("name");
  }

  private static QName get(String local) {
    return CACHE.computeIfAbsent(local, l -> new QName(NS, l, PREFIX));
  }
}
