// Start of user code Copyright
/*
 * Copyright (c) 2025 Contributors to the Eclipse Foundation
 *
 * See the NOTICE file(s) distributed with this work for additional
 * information regarding copyright ownership.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Distribution License 1.0 which is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Simple
 *
 * This file is generated by Lyo Designer (https://www.eclipse.org/lyo/)
 */
// End of user code

package org.eclipse.lyo.oslc.domains;

import java.util.concurrent.ConcurrentHashMap;
import javax.xml.namespace.QName;

// Start of user code imports
// End of user code

public class Prov {
  private static final ConcurrentHashMap<String, QName> CACHE = new ConcurrentHashMap<>();

  public static final String NS = ProvVocabularyConstants.PROVENANCE_NAMSPACE;
  public static final String PREFIX = ProvVocabularyConstants.PROVENANCE_NAMSPACE_PREFIX;

  // static class
  private Prov() {}

  public static QName of(String local) {
    return get(local);
  }

  /**
   * A resource from which this version was derived. This is likely to reference a different concept resource; use of prov:wasRevisionOf is recommended to indicate an earlier version of the same concept resource. The subject of each instance of this property must be the concept resource URI; the object can be a version resource URI, or a concept resource URI (possibly for a non-versioned resource).
   */
  public static final String WASDERIVEDFROM_PROP = NS + "wasDerivedFrom";

  /**
   * A resource from which this version was derived. This is likely to reference an earlier version of the same concept resource; use of prov:wasDerivedFrom is recommended to indicate an earlier version of a different concept resource. The subject of each instance of this property must be the concept resource URI; the object is likely to be a version resource URI.
   */
  public static final String WASREVISIONOF_PROP = NS + "wasRevisionOf";

  /**
   * A resource from which this version was derived. This is likely to reference a different concept resource; use of prov:wasRevisionOf is recommended to indicate an earlier version of the same concept resource. The subject of each instance of this property must be the concept resource URI; the object can be a version resource URI, or a concept resource URI (possibly for a non-versioned resource).
   */
  public static QName wasDerivedFrom() {
    return get("wasDerivedFrom");
  }

  /**
   * A resource from which this version was derived. This is likely to reference an earlier version of the same concept resource; use of prov:wasDerivedFrom is recommended to indicate an earlier version of a different concept resource. The subject of each instance of this property must be the concept resource URI; the object is likely to be a version resource URI.
   */
  public static QName wasRevisionOf() {
    return get("wasRevisionOf");
  }

  private static QName get(String local) {
    return CACHE.computeIfAbsent(local, l -> new QName(NS, l));
  }
}
