// Start of user code Copyright
/*
 * Copyright (c) 2025 Contributors to the Eclipse Foundation
 *
 * See the NOTICE file(s) distributed with this work for additional
 * information regarding copyright ownership.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0, or the Eclipse Distribution License 1.0
 * which is available at http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: EPL-2.0 OR BSD-3-Clause
 *
 * This file is generated by Lyo Designer (https://www.eclipse.org/lyo/)
 */
// End of user code

package org.eclipse.lyo.oslc.domains;

// spotless:off
import org.eclipse.lyo.oslc4j.core.model.OslcConstants;
import javax.xml.namespace.QName;
import java.util.concurrent.ConcurrentHashMap;

// Start of user code imports
// End of user code
// spotless:on

public class RdfsVocabularyConstants
{
    // Start of user code user constants
    // End of user code

    private static final ConcurrentHashMap<String, QName> CACHE = new ConcurrentHashMap<>();

    /**
     * @deprecated Use {@link #NS} instead.
     */
    @Deprecated
    public static final String RDFS_NAMSPACE = "http://www.w3.org/2000/01/rdf-schema#";

    /**
     * @deprecated Use {@link #PREFIX} instead.
     */
    @Deprecated
    public static final String RDFS_NAMSPACE_PREFIX = "rdfs";

    public static final String NS = "http://www.w3.org/2000/01/rdf-schema#";
    public static final String PREFIX = "rdfs";

    // static class
    private RdfsVocabularyConstants() {}

    public static QName of(String local) { return get(local); }

    public static final String RDFSCLASS_LOCAL_NAME = "RdfsClass";
    /**
     * The class resource, everything.
     */
    public static final String RDFSCLASS_CLASS = NS + RDFSCLASS_LOCAL_NAME;

    /**
     * A description of the subject resource.
     */
    public static final String COMMENT_PROP = NS + "comment";
    /**
     * A human-readable name for the subject.
     */
    public static final String LABEL_PROP = NS + "label";
    /**
     * A member of the subject resource.
     */
    public static final String MEMBER_PROP = NS + "member";
    /**
     * Further information about the subject resource.
     */
    public static final String SEEALSO_PROP = NS + "seeAlso";
    /**
     * The subject is a subclass of a class.
     */
    public static final String SUBCLASSOF_PROP = NS + "subClassOf";

    /**
     * A description of the subject resource.
     */
    public static QName comment() { return get("comment"); }
    /**
     * A human-readable name for the subject.
     */
    public static QName label() { return get("label"); }
    /**
     * A member of the subject resource.
     */
    public static QName member() { return get("member"); }
    /**
     * Further information about the subject resource.
     */
    public static QName seeAlso() { return get("seeAlso"); }
    /**
     * The subject is a subclass of a class.
     */
    public static QName subClassOf() { return get("subClassOf"); }

    private static QName get(String local) {
        return CACHE.computeIfAbsent(local, l -> new QName(NS, l, PREFIX));
    }
}
