// Start of user code Copyright
/*
 * Copyright (c) 2025 Contributors to the Eclipse Foundation
 *
 * See the NOTICE file(s) distributed with this work for additional
 * information regarding copyright ownership.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0, or the Eclipse Distribution License 1.0
 * which is available at http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: EPL-2.0 OR BSD-3-Clause
 *
 * This file is generated by Lyo Designer (https://www.eclipse.org/lyo/)
 */
// End of user code

package org.eclipse.lyo.oslc.domains;

// spotless:off
import org.eclipse.lyo.oslc4j.core.model.OslcConstants;
import javax.xml.namespace.QName;
import java.util.concurrent.ConcurrentHashMap;

// Start of user code imports
// End of user code
// spotless:on

public class RdfVocabularyConstants
{
    // Start of user code user constants
    // End of user code

    private static final ConcurrentHashMap<String, QName> CACHE = new ConcurrentHashMap<>();

    /**
     * @deprecated Use {@link #NS} instead.
     */
    @Deprecated
    public static final String RDF_NAMSPACE = "http://www.w3.org/1999/02/22-rdf-syntax-ns#";

    /**
     * @deprecated Use {@link #PREFIX} instead.
     */
    @Deprecated
    public static final String RDF_NAMSPACE_PREFIX = "rdf";

    public static final String NS = "http://www.w3.org/1999/02/22-rdf-syntax-ns#";
    public static final String PREFIX = "rdf";

    // static class
    private RdfVocabularyConstants() {}

    public static QName of(String local) { return get(local); }


    /**
     * The subject is an instance of a class.
     */
    public static final String TYPE_PROP = NS + "type";
    /**
     * Idiomatic property used for structured values.
     */
    public static final String VALUE_PROP = NS + "value";

    /**
     * The subject is an instance of a class.
     */
    public static QName type() { return get("type"); }
    /**
     * Idiomatic property used for structured values.
     */
    public static QName value() { return get("value"); }

    private static QName get(String local) {
        return CACHE.computeIfAbsent(local, l -> new QName(NS, l, PREFIX));
    }
}
