<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="toolchain" nsURI="http://org.eclipse.lyo/oslc4j/toolChain" nsPrefix="oslc4j_tc">
  <eClassifiers xsi:type="ecore:EClass" name="Toolchain">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="New ToolChain"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="adaptorInterfaces" upperBound="-1"
        eType="ecore:EClass adaptorInterface.ecore#//AdaptorInterface" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="specification" lowerBound="1"
        eType="ecore:EClass adaptorInterface.ecore#//Specification" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
