// Start of user code Copyright
/*
 * Copyright (c) 2020 Contributors to the Eclipse Foundation
 *
 * See the NOTICE file(s) distributed with this work for additional
 * information regarding copyright ownership.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Distribution License 1.0 which is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Simple
 *
 * This file is generated by Lyo Designer (https://www.eclipse.org/lyo/)
 */
// End of user code

package org.eclipse.lyo.oslc.domains.promcode;

import java.util.Date;
import java.util.Set;
import org.eclipse.lyo.oslc4j.core.annotation.OslcName;
import org.eclipse.lyo.oslc4j.core.annotation.OslcNamespace;
import org.eclipse.lyo.oslc4j.core.annotation.OslcOccurs;
import org.eclipse.lyo.oslc4j.core.annotation.OslcPropertyDefinition;
import org.eclipse.lyo.oslc4j.core.annotation.OslcRange;
import org.eclipse.lyo.oslc4j.core.annotation.OslcReadOnly;
import org.eclipse.lyo.oslc4j.core.annotation.OslcResourceShape;
import org.eclipse.lyo.oslc4j.core.annotation.OslcValueType;
import org.eclipse.lyo.oslc4j.core.model.Link;
import org.eclipse.lyo.oslc4j.core.model.Occurs;
import org.eclipse.lyo.oslc4j.core.model.ValueType;

// Start of user code imports
// End of user code

@OslcNamespace(Oslc_promcodeDomainConstants.WORKITEM_NAMESPACE)
@OslcName(Oslc_promcodeDomainConstants.WORKITEM_LOCALNAME)
@OslcResourceShape(
        title = "WorkItem Shape",
        description =
                "A work item describes work to be performed in a project delivery contract. It adds"
                    + " detail to the description of work that is described by a scope item. These"
                    + " details typically include cost, schedule, and resource requirements. The"
                    + " set of all work items in a project form a work breakdown structure.",
        describes = Oslc_promcodeDomainConstants.WORKITEM_TYPE)
public interface IWorkItem {

    public void addRequiredBy(final Link requiredBy);

    @OslcName("actualEndDate")
    @OslcPropertyDefinition(Oslc_promcodeDomainConstants.PROMCODE_NAMSPACE + "actualEndDate")
    @OslcOccurs(Occurs.ZeroOrOne)
    @OslcValueType(ValueType.DateTime)
    @OslcReadOnly(false)
    public Date getActualEndDate();

    @OslcName("actualStartDate")
    @OslcPropertyDefinition(Oslc_promcodeDomainConstants.PROMCODE_NAMSPACE + "actualStartDate")
    @OslcOccurs(Occurs.ZeroOrOne)
    @OslcValueType(ValueType.DateTime)
    @OslcReadOnly(false)
    public Date getActualStartDate();

    @OslcName("isPartOf")
    @OslcPropertyDefinition(Oslc_promcodeDomainConstants.PROMCODE_NAMSPACE + "isPartOf")
    @OslcOccurs(Occurs.ZeroOrOne)
    @OslcValueType(ValueType.Resource)
    @OslcRange({Oslc_promcodeDomainConstants.WORKITEM_TYPE})
    @OslcReadOnly(false)
    public Link getIsPartOf();

    @OslcName("plannedEndDate")
    @OslcPropertyDefinition(Oslc_promcodeDomainConstants.PROMCODE_NAMSPACE + "plannedEndDate")
    @OslcOccurs(Occurs.ZeroOrOne)
    @OslcValueType(ValueType.DateTime)
    @OslcReadOnly(false)
    public Date getPlannedEndDate();

    @OslcName("plannedStartDate")
    @OslcPropertyDefinition(Oslc_promcodeDomainConstants.PROMCODE_NAMSPACE + "plannedStartDate")
    @OslcOccurs(Occurs.ZeroOrOne)
    @OslcValueType(ValueType.DateTime)
    @OslcReadOnly(false)
    public Date getPlannedStartDate();

    @OslcName("representedBy")
    @OslcPropertyDefinition(Oslc_promcodeDomainConstants.PROMCODE_NAMSPACE + "representedBy")
    @OslcOccurs(Occurs.ZeroOrOne)
    @OslcValueType(ValueType.Resource)
    @OslcReadOnly(false)
    public Link getRepresentedBy();

    @OslcName("requiredBy")
    @OslcPropertyDefinition(Oslc_promcodeDomainConstants.PROMCODE_NAMSPACE + "requiredBy")
    @OslcOccurs(Occurs.ZeroOrMany)
    @OslcValueType(ValueType.Resource)
    @OslcRange({
        Oslc_promcodeDomainConstants.SCOPEITEM_TYPE,
        Oslc_promcodeDomainConstants.ARTIFACT_TYPE
    })
    @OslcReadOnly(false)
    public Set<Link> getRequiredBy();

    public void setActualEndDate(final Date actualEndDate);

    public void setActualStartDate(final Date actualStartDate);

    public void setIsPartOf(final Link isPartOf);

    public void setPlannedEndDate(final Date plannedEndDate);

    public void setPlannedStartDate(final Date plannedStartDate);

    public void setRepresentedBy(final Link representedBy);

    public void setRequiredBy(final Set<Link> requiredBy);
}
