name: 'Update README'
on:
  pull_request:
    paths:
      - 'tools/readme-matrix/**'
permissions:
  contents: write
jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Run update-readme script
        run: tools/readme-matrix/update-readme.sh

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add README.md
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m 'Update README.md'
            git push
          else
            echo "No changes to commit"
          fi
