name: Rebase
on:
  schedule:
    - cron:  '40 7 * * *'
  workflow_dispatch:

jobs:
  rebase:
    runs-on: ubuntu-latest
    steps:
      - uses: peter-evans/rebase@v2
        with:
          exclude-labels: |
            ci:norebase
            dependencies
          exclude-drafts: true
