// Start of user code Copyright
/*
 * Copyright (c) 2020 Contributors to the Eclipse Foundation
 *
 * See the NOTICE file(s) distributed with this work for additional
 * information regarding copyright ownership.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Distribution License 1.0 which is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Simple
 *
 * This file is generated by Lyo Designer (https://www.eclipse.org/lyo/)
 */
// End of user code

package org.eclipse.lyo.oslc4j.core.model;

// spotless:off
import org.eclipse.lyo.oslc4j.core.model.OslcConstants;


// Start of user code imports
// End of user code
// spotless:on

public interface OslcDomainConstants {
  // Start of user code user constants
  // End of user code

  /**
   * @deprecated use {@link OslcDomainConstants#OSLC_NAMSPACE} or {@link OslcDomainConstants#OSLC_DOMAIN_NAME} instead
   */
  @Deprecated(since = "5.0.1")
  public static String OSLC_DOMAIN = "http://open-services.net/ns/core#";

  public static String OSLC_DOMAIN_NAME = "OSLC";
  public static String OSLC_NAMSPACE =
      "http://open-services.net/ns/core#"; // Vocabulary namespace for the resources and resource
  // properties, when no explicit vocabulary (describes, or
  // propertyDefinition) is defined
  public static String OSLC_NAMSPACE_PREFIX =
      "oslc"; // Vocabulary prefix for the resources and resource properties, when no explicit
  // vocabulary (describes, or propertyDefinition) is defined

  public static String ALLOWEDVALUES_PATH =
      "allowedValues"; // the relative path of the resource shape URL.
  public static String ALLOWEDVALUES_NAMESPACE =
      OslcDomainConstants.OSLC_NAMSPACE; // namespace of the rdfs:class the resource describes
  public static String ALLOWEDVALUES_LOCALNAME =
      "AllowedValues"; // localName of the rdfs:class the resource describes
  public static String ALLOWEDVALUES_TYPE =
      ALLOWEDVALUES_NAMESPACE
          + ALLOWEDVALUES_LOCALNAME; // fullname of the rdfs:class the resource describes
  public static String CREATIONFACTORY_PATH =
      "creationFactory"; // the relative path of the resource shape URL.
  public static String CREATIONFACTORY_NAMESPACE =
      OslcDomainConstants.OSLC_NAMSPACE; // namespace of the rdfs:class the resource describes
  public static String CREATIONFACTORY_LOCALNAME =
      "CreationFactory"; // localName of the rdfs:class the resource describes
  public static String CREATIONFACTORY_TYPE =
      CREATIONFACTORY_NAMESPACE
          + CREATIONFACTORY_LOCALNAME; // fullname of the rdfs:class the resource describes
  public static String DIALOG_PATH = "dialog"; // the relative path of the resource shape URL.
  public static String DIALOG_NAMESPACE =
      OslcDomainConstants.OSLC_NAMSPACE; // namespace of the rdfs:class the resource describes
  public static String DIALOG_LOCALNAME =
      "Dialog"; // localName of the rdfs:class the resource describes
  public static String DIALOG_TYPE =
      DIALOG_NAMESPACE + DIALOG_LOCALNAME; // fullname of the rdfs:class the resource describes
  public static String DISCUSSION_PATH =
      "discussion"; // the relative path of the resource shape URL.
  public static String DISCUSSION_NAMESPACE =
      OslcDomainConstants.OSLC_NAMSPACE; // namespace of the rdfs:class the resource describes
  public static String DISCUSSION_LOCALNAME =
      "Discussion"; // localName of the rdfs:class the resource describes
  public static String DISCUSSION_TYPE =
      DISCUSSION_NAMESPACE
          + DISCUSSION_LOCALNAME; // fullname of the rdfs:class the resource describes
  public static String PROPERTY_PATH = "property"; // the relative path of the resource shape URL.
  public static String PROPERTY_NAMESPACE =
      OslcDomainConstants.OSLC_NAMSPACE; // namespace of the rdfs:class the resource describes
  public static String PROPERTY_LOCALNAME =
      "Property"; // localName of the rdfs:class the resource describes
  public static String PROPERTY_TYPE =
      PROPERTY_NAMESPACE + PROPERTY_LOCALNAME; // fullname of the rdfs:class the resource describes
  public static String PUBLISHER_PATH = "publisher"; // the relative path of the resource shape URL.
  public static String PUBLISHER_NAMESPACE =
      OslcDomainConstants.OSLC_NAMSPACE; // namespace of the rdfs:class the resource describes
  public static String PUBLISHER_LOCALNAME =
      "Publisher"; // localName of the rdfs:class the resource describes
  public static String PUBLISHER_TYPE =
      PUBLISHER_NAMESPACE
          + PUBLISHER_LOCALNAME; // fullname of the rdfs:class the resource describes
  public static String QUERYCAPABILITY_PATH =
      "queryCapability"; // the relative path of the resource shape URL.
  public static String QUERYCAPABILITY_NAMESPACE =
      OslcDomainConstants.OSLC_NAMSPACE; // namespace of the rdfs:class the resource describes
  public static String QUERYCAPABILITY_LOCALNAME =
      "QueryCapability"; // localName of the rdfs:class the resource describes
  public static String QUERYCAPABILITY_TYPE =
      QUERYCAPABILITY_NAMESPACE
          + QUERYCAPABILITY_LOCALNAME; // fullname of the rdfs:class the resource describes
  public static String RESOURCESHAPE_PATH =
      "resourceShape"; // the relative path of the resource shape URL.
  public static String RESOURCESHAPE_NAMESPACE =
      OslcDomainConstants.OSLC_NAMSPACE; // namespace of the rdfs:class the resource describes
  public static String RESOURCESHAPE_LOCALNAME =
      "ResourceShape"; // localName of the rdfs:class the resource describes
  public static String RESOURCESHAPE_TYPE =
      RESOURCESHAPE_NAMESPACE
          + RESOURCESHAPE_LOCALNAME; // fullname of the rdfs:class the resource describes
  public static String SERVICE_PATH = "service"; // the relative path of the resource shape URL.
  public static String SERVICE_NAMESPACE =
      OslcDomainConstants.OSLC_NAMSPACE; // namespace of the rdfs:class the resource describes
  public static String SERVICE_LOCALNAME =
      "Service"; // localName of the rdfs:class the resource describes
  public static String SERVICE_TYPE =
      SERVICE_NAMESPACE + SERVICE_LOCALNAME; // fullname of the rdfs:class the resource describes
  public static String SERVICEPROVIDER_PATH =
      "serviceProvider"; // the relative path of the resource shape URL.
  public static String SERVICEPROVIDER_NAMESPACE =
      OslcDomainConstants.OSLC_NAMSPACE; // namespace of the rdfs:class the resource describes
  public static String SERVICEPROVIDER_LOCALNAME =
      "ServiceProvider"; // localName of the rdfs:class the resource describes
  public static String SERVICEPROVIDER_TYPE =
      SERVICEPROVIDER_NAMESPACE
          + SERVICEPROVIDER_LOCALNAME; // fullname of the rdfs:class the resource describes
  public static String SERVICEPROVIDERCATALOG_PATH =
      "serviceProviderCatalog"; // the relative path of the resource shape URL.
  public static String SERVICEPROVIDERCATALOG_NAMESPACE =
      OslcDomainConstants.OSLC_NAMSPACE; // namespace of the rdfs:class the resource describes
  public static String SERVICEPROVIDERCATALOG_LOCALNAME =
      "ServiceProviderCatalog"; // localName of the rdfs:class the resource describes
  public static String SERVICEPROVIDERCATALOG_TYPE =
      SERVICEPROVIDERCATALOG_NAMESPACE
          + SERVICEPROVIDERCATALOG_LOCALNAME; // fullname of the rdfs:class the resource describes
}
