// Start of user code Copyright
/*
 * Copyright (c) 2020 Contributors to the Eclipse Foundation
 *
 * See the NOTICE file(s) distributed with this work for additional
 * information regarding copyright ownership.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Distribution License 1.0 which is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Simple
 *
 * This file is generated by Lyo Designer (https://www.eclipse.org/lyo/)
 */
// End of user code

package org.eclipse.lyo.oslc4j.provider.jena.shapefactory.resources;

import java.net.URI;
import java.net.URISyntaxException;
import org.eclipse.lyo.oslc4j.core.OSLC4JUtils;
import org.eclipse.lyo.oslc4j.core.annotation.OslcName;
import org.eclipse.lyo.oslc4j.core.annotation.OslcNamespace;
import org.eclipse.lyo.oslc4j.core.annotation.OslcOccurs;
import org.eclipse.lyo.oslc4j.core.annotation.OslcPropertyDefinition;
import org.eclipse.lyo.oslc4j.core.annotation.OslcRange;
import org.eclipse.lyo.oslc4j.core.annotation.OslcReadOnly;
import org.eclipse.lyo.oslc4j.core.annotation.OslcResourceShape;
import org.eclipse.lyo.oslc4j.core.annotation.OslcValueType;
import org.eclipse.lyo.oslc4j.core.exception.OslcCoreApplicationException;
import org.eclipse.lyo.oslc4j.core.model.AbstractResource;
import org.eclipse.lyo.oslc4j.core.model.Occurs;
import org.eclipse.lyo.oslc4j.core.model.OslcConstants;
import org.eclipse.lyo.oslc4j.core.model.ResourceShape;
import org.eclipse.lyo.oslc4j.core.model.ResourceShapeFactory;
import org.eclipse.lyo.oslc4j.core.model.ValueType;

// Start of user code preClassCode
// End of user code

// Start of user code classAnnotations
// THis class is invalid since the "referencesAsResource" attribute refers to a class, yet it is
// annotated to be to be represented as a Resource/Link.
// End of user code
@OslcNamespace(Oslc_sdDomainConstants.SHAPEWITHWRONGREFERENCETORESOURCE_NAMESPACE)
@OslcName(Oslc_sdDomainConstants.SHAPEWITHWRONGREFERENCETORESOURCE_LOCALNAME)
@OslcResourceShape(
        title = "ShapeWithWrongReferenceToResource Resource Shape",
        describes = Oslc_sdDomainConstants.SHAPEWITHWRONGREFERENCETORESOURCE_TYPE)
public class ShapeWithWrongReferenceToResource extends AbstractResource
        implements IShapeWithWrongReferenceToResource {
    // Start of user code attributeAnnotation:referencesAsResource
    // End of user code
    private ReferencedShape referencesAsResource;
    // Start of user code attributeAnnotation:identifier
    // End of user code
    private String identifier;

    // Start of user code classAttributes
    // End of user code
    // Start of user code classMethods
    // End of user code
    public ShapeWithWrongReferenceToResource() {
        super();

        // Start of user code constructor1
        // End of user code
    }

    public ShapeWithWrongReferenceToResource(final URI about) {
        super(about);

        // Start of user code constructor2
        // End of user code
    }

    public static ResourceShape createResourceShape()
            throws OslcCoreApplicationException, URISyntaxException {
        return ResourceShapeFactory.createResourceShape(
                OSLC4JUtils.getServletURI(),
                OslcConstants.PATH_RESOURCE_SHAPES,
                Oslc_sdDomainConstants.SHAPEWITHWRONGREFERENCETORESOURCE_PATH,
                ShapeWithWrongReferenceToResource.class);
    }

    public String toString() {
        return toString(false);
    }

    public String toString(boolean asLocalResource) {
        String result = "";
        // Start of user code toString_init
        // End of user code

        if (asLocalResource) {
            result =
                    result
                            + "{a Local ShapeWithWrongReferenceToResource Resource} - update"
                            + " ShapeWithWrongReferenceToResource.toString() to present resource as"
                            + " desired.";
            // Start of user code toString_bodyForLocalResource
            // End of user code
        } else {
            result = String.valueOf(getAbout());
        }

        // Start of user code toString_finalize
        // End of user code

        return result;
    }

    // Start of user code getterAnnotation:referencesAsResource
    // End of user code
    @OslcName("referencesAsResource")
    @OslcPropertyDefinition(Oslc_sdDomainConstants.SPECDOMAIN_NAMSPACE + "referencesAsResource")
    @OslcOccurs(Occurs.ExactlyOne)
    @OslcValueType(ValueType.Resource)
    @OslcRange({Oslc_sdDomainConstants.REFERENCEDSHAPE_TYPE})
    @OslcReadOnly(false)
    public ReferencedShape getReferencesAsResource() {
        // Start of user code getterInit:referencesAsResource
        // End of user code
        return referencesAsResource;
    }

    // Start of user code getterAnnotation:identifier
    // End of user code
    @OslcName("identifier")
    @OslcPropertyDefinition(Oslc_sdDomainConstants.SPECDOMAIN_NAMSPACE + "identifier")
    @OslcOccurs(Occurs.ExactlyOne)
    @OslcValueType(ValueType.String)
    @OslcReadOnly(false)
    public String getIdentifier() {
        // Start of user code getterInit:identifier
        // End of user code
        return identifier;
    }

    // Start of user code setterAnnotation:referencesAsResource
    // End of user code
    public void setReferencesAsResource(final ReferencedShape referencesAsResource) {
        // Start of user code setterInit:referencesAsResource
        // End of user code
        this.referencesAsResource = referencesAsResource;

        // Start of user code setterFinalize:referencesAsResource
        // End of user code
    }

    // Start of user code setterAnnotation:identifier
    // End of user code
    public void setIdentifier(final String identifier) {
        // Start of user code setterInit:identifier
        // End of user code
        this.identifier = identifier;

        // Start of user code setterFinalize:identifier
        // End of user code
    }
}
